import { Movie } from './types';

export const NAVIGATION_LINKS = [
  { name: 'Beranda', href: '/' },
  { name: 'Genre', href: '/genres' },
  { name: 'All List', href: '/all-movies' },
  { name: 'Baru & Populer', href: '/new-popular' },
];

// Fix: Added the missing ALL_MOVIES constant to provide mock data for various pages.
// This resolves import errors in DetailPage, NewPopularPage, SearchResultsPage, and AllMoviesPage.
export const ALL_MOVIES: Movie[] = [
  {
    id: 1,
    title: 'Dune: Part Two',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    description: 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.',
    genre: ['Sci-Fi', 'Adventure'],
    releaseYear: 2024,
    rating: 8.3,
    streamingSources: [{ platform: 'HBO Max', url: '#' }],
  },
  {
    id: 2,
    title: 'Oppenheimer',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    description: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
    genre: ['Drama', 'History', 'Thriller'],
    releaseYear: 2023,
    rating: 8.6,
    streamingSources: [{ platform: 'Peacock', url: '#' }],
  },
  {
    id: 3,
    title: 'Godzilla x Kong: The New Empire',
    posterUrl: 'https://image.tmdb.org/t/p/w500/tMefBSflR6PGsBKJCWeIoAaonA.jpg',
    description: 'Two ancient titans, Godzilla and Kong, clash in an epic battle as humans unravel their intertwined origins and connection to Skull Island\'s mysteries.',
    genre: ['Action', 'Sci-Fi', 'Adventure'],
    releaseYear: 2024,
    rating: 6.7,
    streamingSources: [{ platform: 'HBO Max', url: '#' }],
  },
  {
    id: 4,
    title: 'Kung Fu Panda 4',
    posterUrl: 'https://image.tmdb.org/t/p/w500/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg',
    description: 'Po must train a new warrior when he\'s chosen to become the spiritual leader of the Valley of Peace. However, when a powerful shape-shifting sorceress sets her eyes on his Staff of Wisdom, he suddenly realizes he\'s going to need some help. Teaming up with a quick-witted corsac fox, Po soon discovers that heroes can be found in the most unexpected places.',
    genre: ['Animation', 'Action', 'Family'],
    releaseYear: 2024,
    rating: 6.9,
    streamingSources: [{ platform: 'Peacock', url: '#' }],
  },
  {
    id: 5,
    title: 'Civil War',
    posterUrl: 'https://image.tmdb.org/t/p/w500/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg',
    description: 'A journey across a dystopian future America, following a team of military-embedded journalists as they race against time to reach DC before rebel factions descend upon the White House.',
    genre: ['Action', 'Thriller', 'War'],
    releaseYear: 2024,
    rating: 7.4,
    streamingSources: [{ platform: 'Amazon Prime', url: '#' }],
  },
  {
    id: 6,
    title: 'The Fall Guy',
    posterUrl: 'https://image.tmdb.org/t/p/w500/aBkqu7gV2MpdvQkO8hEg2w7q8GI.jpg',
    description: 'A down-and-out stuntman must find the missing star of his ex-girlfriend\'s blockbuster film.',
    genre: ['Action', 'Comedy'],
    releaseYear: 2024,
    rating: 7.3,
    streamingSources: [{ platform: 'Apple TV+', url: '#' }],
  },
  {
    id: 7,
    title: 'Kingdom of the Planet of the Apes',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gKkl37BQuKTanygYQG1pyYgLVgf.jpg',
    description: 'Several generations in the future following Caesar\'s reign, apes are now the dominant species and live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all that he has known about the past and to make choices that will define a future for apes and humans alike.',
    genre: ['Sci-Fi', 'Adventure', 'Action'],
    releaseYear: 2024,
    rating: 7.2,
    streamingSources: [{ platform: 'Hulu', url: '#' }],
  },
  {
    id: 8,
    title: 'Past Lives',
    posterUrl: 'https://image.tmdb.org/t/p/w500/k3waq02AhM2Q283G2M6gt7pS2om.jpg',
    description: 'Nora and Hae Sung, two deeply connected childhood friends, are wrest apart after Nora\'s family emigrates from South Korea. Twenty years later, they are reunited for one fateful week as they confront notions of love, destiny and the choices that make a life.',
    genre: ['Romance', 'Drama'],
    releaseYear: 2023,
    rating: 7.9,
    streamingSources: [{ platform: 'Netflix', url: '#' }],
  },
  {
    id: 9,
    title: 'Spider-Man: Across the Spider-Verse',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    description: 'After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must redefine what it means to be a hero.',
    genre: ['Animation', 'Action', 'Adventure'],
    releaseYear: 2023,
    rating: 8.4,
    streamingSources: [{ platform: 'Netflix', url: '#' }],
  },
  {
    id: 10,
    title: 'Poor Things',
    posterUrl: 'https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg',
    description: 'Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.',
    genre: ['Sci-Fi', 'Romance', 'Comedy', 'Drama'],
    releaseYear: 2023,
    rating: 8.0,
    streamingSources: [{ platform: 'Hulu', url: '#' }],
  },
  {
    id: 11,
    title: 'Anatomy of a Fall',
    posterUrl: 'https://image.tmdb.org/t/p/w500/kQs6keHeMwA2hlK0Vci6IkvasfS.jpg',
    description: 'A woman is suspected of her husband\'s murder, and their blind son faces a moral dilemma as the sole witness.',
    genre: ['Thriller', 'Crime', 'Drama'],
    releaseYear: 2023,
    rating: 7.7,
    streamingSources: [{ platform: 'Hulu', url: '#' }],
  },
  {
    id: 12,
    title: 'The Holdovers',
    posterUrl: 'https://image.tmdb.org/t/p/w500/prHE2QDpcV6CE57dY4ufS72zriD.jpg',
    description: 'A cranky history teacher at a remote prep school is forced to remain on campus over the holidays with a troubled student who has no place to go.',
    genre: ['Comedy', 'Drama'],
    releaseYear: 2023,
    rating: 7.9,
    streamingSources: [{ platform: 'Peacock', url: '#' }],
  },
  {
    id: 13,
    title: 'Killers of the Flower Moon',
    posterUrl: 'https://image.tmdb.org/t/p/w500/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg',
    description: 'When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one—until the FBI steps in to unravel the mystery.',
    genre: ['Crime', 'Drama', 'History'],
    releaseYear: 2023,
    rating: 7.6,
    streamingSources: [{ platform: 'Apple TV+', url: '#' }],
  },
  {
    id: 14,
    title: 'The Boy and the Heron',
    posterUrl: 'https://image.tmdb.org/t/p/w500/f4o4c45Keu35h2aQ2a5K2S1Z2p.jpg',
    description: 'While the Second World War rages, the teenage Mahito, haunted by his mother\'s tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who happens to be his mother\'s younger sister. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the "long-awaited one."',
    genre: ['Animation', 'Fantasy', 'Adventure'],
    releaseYear: 2023,
    rating: 7.5,
    streamingSources: [{ platform: 'HBO Max', url: '#' }],
  },
  {
    id: 15,
    title: 'John Wick: Chapter 4',
    posterUrl: 'https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
    description: 'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
    genre: ['Action', 'Thriller', 'Crime'],
    releaseYear: 2023,
    rating: 7.8,
    streamingSources: [{ platform: 'Starz', url: '#' }],
  },
  {
    id: 16,
    title: 'Guardians of the Galaxy Vol. 3',
    posterUrl: 'https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg',
    description: 'Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.',
    genre: ['Sci-Fi', 'Adventure', 'Action'],
    releaseYear: 2023,
    rating: 8.0,
    streamingSources: [{ platform: 'Disney+', url: '#' }],
  },
  {
    id: 17,
    title: 'Mission: Impossible - Dead Reckoning Part One',
    posterUrl: 'https://image.tmdb.org/t/p/w500/NNxYkU70HPurnNCSiCjYUkEgdNe.jpg',
    description: 'Ethan Hunt and his IMF team embark on their most dangerous mission yet: To track down a terrifying new weapon that threatens all of humanity before it falls into the wrong hands.',
    genre: ['Action', 'Thriller', 'Adventure'],
    releaseYear: 2023,
    rating: 7.7,
    streamingSources: [{ platform: 'Paramount+', url: '#' }],
  },
  {
    id: 18,
    title: 'The Creator',
    posterUrl: 'https://image.tmdb.org/t/p/w500/vB8o2p4ETnrfiWEgVxHmHWP9yRl.jpg',
    description: 'Amid a future war between the human race and the forces of artificial intelligence, a hardened ex-special forces agent grieving the disappearance of his wife, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI who has developed a mysterious weapon with the power to end the war—and mankind itself.',
    genre: ['Sci-Fi', 'Action', 'Thriller'],
    releaseYear: 2023,
    rating: 7.1,
    streamingSources: [{ platform: 'Hulu', url: '#' }],
  },
  {
    id: 19,
    title: 'The Killer',
    posterUrl: 'https://image.tmdb.org/t/p/w500/e7Jvsry47JJQruuezjU2X1Z6J77.jpg',
    description: 'After a fateful near-miss, an assassin battles his employers, and himself, on an international manhunt he insists isn\'t personal.',
    genre: ['Thriller', 'Action', 'Crime'],
    releaseYear: 2023,
    rating: 6.8,
    streamingSources: [{ platform: 'Netflix', url: '#' }],
  },
  {
    id: 20,
    title: 'Barbie',
    posterUrl: 'https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    description: 'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.',
    genre: ['Comedy', 'Adventure', 'Fantasy'],
    releaseYear: 2023,
    rating: 7.2,
    streamingSources: [{ platform: 'HBO Max', url: '#' }],
  },
];
